blogapp/urls.py
from django.urls import path
from .views import home_views,blog_views

app_name = 'blogapp'
urlpatterns = [
   path('',home_views,name="home"),
   path('blog',blog_views,name="blog"),

]

blogproject/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path,include
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('blogapp.urls')),
    #restframeworkapi
    
]
urlpatterns += static(settings.STATIC_URL,document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

blogapp/models.py
from django.db import models
from django.contrib.auth.models import User
# Create your models here.


class Author(models.Model):
    mobile = models.CharField(max_length=50)
    name = models.CharField(max_length=200)
    address = models.CharField(max_length=200, null=True, blank=True)
    photo = models.ImageField(upload_to='blog', null=True, blank=True)

    def __str__(self):
        return self.name

class Blog(models.Model):
	title=models.CharField(max_length=100)
	author=models.ForeignKey(Author,on_delete=models.CASCADE)
	description=models.TextField()
	image=models.ImageField(upload_to="blog")
	created_at=models.DateTimeField(auto_now_add=True)
	updated_at=models.DateTimeField(auto_now_add=True, null=True, blank=True)

	def __self__(self):
		return self.title

blogapp/views.py
from django.shortcuts import render,redirect
from django.views.generic import *
from django.urls import reverse_lazy, reverse
from django.http import JsonResponse
from datetime import datetime, timedelta
from django.contrib.auth.models import User
from django.http import HttpResponse, HttpResponseRedirect
from .models import Blog,Author
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth import logout, authenticate, login
from .forms import *
from django.contrib import messages
from django.contrib.auth.decorators import login_required

# Create your views here.
def home_views(request):



	return render(request,'home.html',{})

def blog_views(request):
	blog=Blog.objects.all()
	context={
	 'allblog':blog
	}


	return render(request,'blog.html',context)

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
  <title>Bootstrap Example</title>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"></script>
  <style type="text/css" href="{% static 'css/style.css' %}"></style>
</head>
<style>
	@import url('https://fonts.googleapis.com/css2?family=Aclonica&display=swap');

.m-f{
  font-family: 'Aclonica', sans-serif;
  text-transform: uppercase;
}
.btn{
  background-color: transparent;
  border: 3px solid #ffffff;
  padding: 15px 35px;
  font-weight: bolder;
  text-decoration: none;
  color: #ffffff;
  margin-right: 15px;
  transition: all 400ms ease-in-out;
}

.btn-fill{
  background-color: #ffffff;
  color: #000000;
}

.btn-fill:hover{
  background-color: #f1c11a;
  border-color: transparent;
}
	*{
  padding: 0;
  margin: 0;
}
body{
  background-image: url(../static/images/back-img.jpg);
  background-size: cover;
  background-attachment: fixed;
  position: relative;
}

main{
  position: absolute;
  top: 0;
  left: 0;
  width: 100%;
}
.header{
  height: 100vh;
  color: #ffffff;
  line-height: 50px;
}
.header-content{
  padding-top: 40vh;
  text-align: center;
}

</style>
<body>

 <main>
    <!-- Header section start -->
    <div class="header">
      <div class="container">
        <div class="header-content">
          <h1 class="m-f">Welcome to blog</h1>
        
          <a href="{% url 'blogapp:blog' %}" class="btn btn-trans">blog</a>
          
        </div>
      </div>
    </div>

{% block content %}

{% endblock %}

</body>
</html>

templates/blog.html
{% load static %}
{% block content %}
<!DOCTYPE html>
<html lang="en">
<head>
  <title>Bootstrap Example</title>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"></script>
  <style type="text/css" href="{% static 'css/style.css' %}"></style>
</head>
<body>
	

<a href="{% url 'blogapp:home' %}" class="btn btn-trans">home</a>

<table class="table table-bordered">
  <thead>
    <tr>
      <th scope="col">SN</th>
      <th scope="col">Title</th>
      <th scope="col">image</th>
      <th scope="col">Author</th>
      <th scope="col">created_at</th>
      <th scope="col">updated_at</th>

    </tr>
  </thead>
<tbody>
{% for blog in allblog %}
    <tr>
      <th scope="row">{{forloop.counter}}</th>
      <td class="text-danger">{{blog.title}}</td>
    
      <td><img src="{{blog.image.url }}" width="50"></td>
      <td class="text-success">{{blog.author.name}} ago</td>
      <td class="text-warning">{{blog.created_at}}</td>
      <td class="text-dark">{{blog.updated_at}}</td>

    </tr>
    
{% endfor %}
    
</tbody>
</table>

</body>
</html>
{% endblock %}

templates/home.html
{% extends 'base.html' %}

{% load static %}
{% block content %}

{% endblock %}